### ISSUE TITLE
Still being maintained? 

### ISSUE THREAD

**Issue by juliedavila** [AutoLogicTechnology/autologic-users#12]
Hi @mrcrilly,

This is probably the _best_ role for *nix user management that I've come across. I did use and recommend it heavily while consulting for Ansible. 

However, I do notice it's become a bit stale so I want to check to see if this is still being maintained, if so, I have a pull request that makes some updated to make this work with the current version of Ansible. And if it isn't maintained, well then I have no issues making a fork.

**Comment by mrcrilly** [comment]
Hi. Sorry. I don't get GitHub notifications so I've only just noticed this.

Please feel free to issue a PR and I will merge it ASAP. I'll probably also move this repository over to my new company, OpsFactory, but I will wait until your PR comes in. Cheers.

**Comment by juliedavila** [comment]
@mrcrilly PR up #13
